Refined P3P solver, and a new implementation for rel_pose_upright_3pt
PoseLib/PoseLib pull request #93
Opened 2024-02-14 21:41 UTC by yaqding

Refined P3P_ding solver. 
Compare with default solver with Newton refinement:
![Screenshot from 2024-02-14 22-25-14](https://github.com/PoseLib/PoseLib/assets/56595403/a41fe4c1-78f8-401e-bbe2-76b04fbfe979)
without Newton refinement:
![Screenshot from 2024-02-14 22-25-43](https://github.com/PoseLib/PoseLib/assets/56595403/e818e2d1-c45b-4393-adb0-d32e53aa1689)
Performance on real dataset. Slight improvements over the existing solvers. First sequence AUC5 89.57 vs 89.48 and more efficient.
Latest implementation:
![Screenshot from 2024-02-14 17-25-23](https://github.com/PoseLib/PoseLib/assets/56595403/e520948a-e97f-474e-9e63-592b7e04634c)
Default P3P solver:
![Screenshot from 2024-02-14 17-25-53](https://github.com/PoseLib/PoseLib/assets/56595403/7449f631-f034-44bb-83f4-1c275069211d)
Original p3p_ding by Mark Shachkov:
![Screenshot from 2024-02-14 18-07-12](https://github.com/PoseLib/PoseLib/assets/56595403/a52b45cb-14ea-44ec-ab45-a134cd15baac)

A new implementation for rel_pose_upright_3pt solver based on intersections of conics.
Default solver:
![thumbnail_image](https://github.com/PoseLib/PoseLib/assets/56595403/7240f1dc-c540-4ef2-806a-7c84029e9646)
New implementation:
![Screenshot from 2024-02-14 22-01-52](https://github.com/PoseLib/PoseLib/assets/56595403/c1f2ee29-df36-48e5-a16c-b3d78e53d281)

2024-02-15 14:23 UTC, pablospe commented
Check C++ formatting:
https://github.com/PoseLib/PoseLib/actions/runs/7876199471/job/21496196436?pr=92

You can run this line at the top-level in the repo:
https://github.com/PoseLib/PoseLib/actions/runs/7876199471/workflow?pr=92#L31

2024-02-15 14:38 UTC, yaqding commented
Thanks! It should be fine now.

2024-02-16 00:03 UTC, S-o-T commented
@yaqding thanks for refinement!

I took a quick look over changes and found out that ensuring BC is largest is enough to make current implementation as stable as lambda twist (according to poselib internal benchmark).

Regarding posebench results - i failed to reproduce numbers you posted, all 4 implementation yielded the same AUC5=89.48 on eth3d_130_dusmanu, but it looks a strange given that current implementation is a bit less stable then lambda twist. I will try to find some time to recheck that.

2024-02-16 00:07 UTC, S-o-T commented on PoseLib/solvers/p3p_ding.cc
> +    std::vector<Eigen::Vector3d> X = X_copy;
Allocating here is not quite optimal, instead, std::array could be used to gain some performance.

2024-02-16 08:28 UTC, yaqding commented on PoseLib/solvers/p3p_ding.cc
> +    std::vector<Eigen::Vector3d> X = X_copy;
Thanks! It improves a bit.

2024-02-16 08:43 UTC, yaqding commented
@S-o-T The little difference in the posebench is possibly due to the different random samples in different machines. After using std::array instead of std::vector, now the runtime is ~209ns.

2024-02-16 10:12 UTC, vlarsson commented on PoseLib/solvers/p3p_common.h
> +inline double cubic_trigonometric_solution(const double alpha, const double beta, const double k2,
I guess these functions are similar to what exists in https://github.com/PoseLib/PoseLib/blob/master/PoseLib/misc/univariate.cc#L74
?
We should probably figure out what is best and put it here

2024-02-16 10:40 UTC, pablospe commented on PoseLib/solvers/p3p_ding.cc
> +            x[0] = x_copy[2];
```
            x[0] = x_copy[2];
            x[2] = x_copy[0];
            X[0] = X_copy[2];
            X[2] = X_copy[0];
```

Remove duplicates

2024-02-16 10:40 UTC, pablospe commented on PoseLib/solvers/p3p_ding.cc
> +    std::array<Eigen::Vector3d,3> X = {X_copy[0], X_copy[1], X_copy[2]};
why is the copy needed? Isn't it a way to swap the columns (efficiently) internally in Eigen?

2024-02-16 10:41 UTC, pablospe commented on PoseLib/solvers/p3p_ding.cc
> +        X[0] = X_copy[1];
also here: `x[0] = x_copy[1];` is twice

2024-02-16 10:42 UTC, pablospe commented on PoseLib/solvers/p3p_ding.cc
>      const double m12 = x[0].dot(x[1]);
wouldn't it be convenient to keep 0-index notation? like have:
```
const double m01 = x[0].dot(x[1]);
```

2024-02-16 10:43 UTC, pablospe commented on PoseLib/solvers/relpose_upright_3pt.cc
> +// Author: Yaqing Ding (yaq.ding@gmail.com).
are you sure you want to keep your email public? :) anyways it is already in this branch. You might need to do a squash and force push, I don't know.

2024-02-16 10:44 UTC, pablospe commented
It seems it is still complaining about the formatting.
https://github.com/PoseLib/PoseLib/actions/runs/7927921250/job/21649068111?pr=93

2024-02-16 12:45 UTC, yaqding commented on PoseLib/solvers/p3p_ding.cc
> +            x[0] = x_copy[2];
The last two rows are capital.

2024-02-16 12:46 UTC, yaqding commented on PoseLib/solvers/p3p_ding.cc
>      const double m12 = x[0].dot(x[1]);
All the parameters renamed .

2024-02-16 12:52 UTC, yaqding commented on PoseLib/solvers/p3p_ding.cc
> +    std::array<Eigen::Vector3d,3> X = {X_copy[0], X_copy[1], X_copy[2]};
I agree, it's not elegant to use additional X_copy, x_copy. The input data is const std::vector<Eigen::Vector3d> &x, it seems that there are no good ways to swap the elements. Or any suggestions?

2024-02-16 12:57 UTC, pablospe commented on PoseLib/solvers/p3p_ding.cc
> +            x[0] = x_copy[2];
ah, thanks!

2024-02-16 13:04 UTC, pablospe commented on PoseLib/solvers/relpose_upright_3pt.cc
> +        if ((n_sols > 0 && G))
double `((`, needed?

2024-10-17 20:23 UTC, vlarsson approved these changes
Looks good to me. We could potentially switch this to be the default p3p solver.

2024-10-18 09:35 UTC, yaqding commented
Did minor changes to set as default solver.

2024-10-18 12:57 UTC, vlarsson commented
Maybe make the older solver available as p3p_lambdatwist as well.

2024-10-18 13:28 UTC, yaqding commented
added now

2024-10-18 20:23 UTC, pablospe requested changes

2024-10-18 20:23 UTC, pablospe commented on PoseLib/solvers/relpose_upright_3pt.cc
> +// Some of the scripts are based on Mark Shachkov (mark.shachkov@gmail.com) and the Lambda-twist P3P implementation
Before merging, I would double-check with Mark two things:
1. Using the code you are mentioning (since this library has BSD library).
2. Adding his email in a public code. I would remove his email.

Note: if it is a total re-implementation I would also rewrite this, perhaps pointing to a publication.

2024-10-18 20:50 UTC, S-o-T commented on PoseLib/solvers/relpose_upright_3pt.cc
> +// Some of the scripts are based on Mark Shachkov (mark.shachkov@gmail.com) and the Lambda-twist P3P implementation
@pablospe Thanks for raising that.

Regarding code authorship credits, i believe that point of convergence could be:
```
Authors: Yaqing Ding
         Mark Shachkov
```

As for my email address: i originally put it there, but I think it's a good idea to remove it.

2024-10-18 22:38 UTC, pablospe approved these changes

2024-10-20 18:55 UTC, merged